/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cameras/{cameraId}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zonas activas de la cámara */
        get: operations["list"];
        /** Guarda las zonas de la cámara (administrador) */
        put: operations["replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de usuarios (administrador) */
        get: operations["users"];
        put?: never;
        /** Crea un operador o administrador (administrador) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versiones del modelo con métricas y quality gate */
        get: operations["list_1"];
        put?: never;
        /** Registra una versión entrenada (RF-13.3) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{version}/artifacts/{artifact}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sube el archivo ONNX del detector o del lector de placas (RF-9.1) */
        post: operations["uploadArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activa una versión que cumple las métricas mínimas (HU-5) */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vuelve a la versión anterior */
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/cameras/{cameraId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sube las tres fotos de evidencia de un reporte (multipart, RF-7.3) */
        post: operations["evidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/cameras/{cameraId}/events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Eventos guardados sin conexión, en orden e idempotentes (RF-8.3) */
        post: operations["events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renueva la sesión vigente antes de que venza */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Genera el secreto del segundo factor del administrador (código QR) */
        post: operations["setupMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activa el segundo factor con un código válido y emite una sesión nueva */
        post: operations["activateMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicio de sesión de funcionarios (JWT de corta duración) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca una alerta como atendida */
        post: operations["acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle con fotos y recorte de la placa (RF-3.2) */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirma o descarta el reporte con motivo (RF-3.3) */
        patch: operations["review"];
        trace?: never;
    };
    "/api/v1/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agregados por minuto, hora o día (horas con más parqueo indebido) */
        get: operations["query"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retraining/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Muestras acumuladas y necesidad de reentrenar (RF-14.3) */
        get: operations["retrainingStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reportes con filtros por fecha, cámara, zona y estado (RF-3.1) */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}/evidence/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Foto de evidencia: entry, report o plate (RF-3.2) */
        get: operations["evidence_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exporta el listado filtrado a PDF o Excel (RF-3.4) */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/cameras/{cameraId}/models/{version}/{artifact}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descarga un archivo ONNX del modelo (RF-15.3) */
        get: operations["modelArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/cameras/{cameraId}/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modelo activo con la huella SHA-256 de cada archivo (RF-9.1) */
        get: operations["activeModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edge/cameras/{cameraId}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuración de zonas y modelo vigente, con ETag (RF-6.2) */
        get: operations["configuration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cámaras con ubicación, estado y dirección del video (PB-01) */
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{cameraId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una cámara */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{cameraId}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detecciones e indicadores en vivo (PB-02, PB-12) */
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alertas de deriva y de reentrenamiento */
        get: operations["alerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ImagePoint: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
        };
        ReplaceZonesRequest: {
            zones: components["schemas"]["ZoneDraft"][];
        };
        ZoneDraft: {
            /** Format: int64 */
            id?: number;
            name: string;
            /** @enum {string} */
            zoneType: "SIDEWALK" | "CORNER" | "GARAGE_ENTRANCE" | "YELLOW_ZONE" | "TRAFFIC_LANE";
            polygon: components["schemas"]["ImagePoint"][];
            /** Format: int32 */
            toleranceSeconds?: number;
            signaled?: boolean;
        };
        ZoneView: {
            /** Format: int64 */
            id?: number;
            cameraId?: string;
            name?: string;
            /** @enum {string} */
            zoneType?: "SIDEWALK" | "CORNER" | "GARAGE_ENTRANCE" | "YELLOW_ZONE" | "TRAFFIC_LANE";
            polygon?: components["schemas"]["ImagePoint"][];
            /** Format: int32 */
            toleranceSeconds?: number;
            signaled?: boolean;
        };
        CreateUserRequest: {
            username: string;
            fullName: string;
            password: string;
            /** @enum {string} */
            role: "OPERATOR" | "ADMINISTRATOR";
        };
        AuthenticatedUser: {
            /** Format: uuid */
            id?: string;
            username?: string;
            fullName?: string;
            /** @enum {string} */
            role?: "OPERATOR" | "ADMINISTRATOR";
        };
        RegisterModelRequest: {
            version: string;
            /** Format: date-time */
            trainedAt: string;
            /** Format: double */
            map50?: number;
            /** Format: double */
            precision?: number;
            /** Format: double */
            recall?: number;
            /** Format: double */
            plateAccuracy?: number;
            detectorObjectKey?: string;
            detectorSha256?: string;
            plateReaderObjectKey?: string;
            plateReaderSha256?: string;
        };
        ModelMetrics: {
            /** Format: double */
            map50?: number;
            /** Format: double */
            precision?: number;
            /** Format: double */
            recall?: number;
            /** Format: double */
            plateAccuracy?: number;
        };
        ModelVersionView: {
            version?: string;
            /** Format: date-time */
            trainedAt?: string;
            metrics?: components["schemas"]["ModelMetrics"];
            verified?: boolean;
            active?: boolean;
            detectorSha256?: string;
            plateReaderSha256?: string;
            qualityGate?: components["schemas"]["Result"];
        };
        Result: {
            passed?: boolean;
            failures?: string[];
        };
        EvidenceKeys: {
            entryPhotoKey: string;
            reportPhotoKey: string;
            platePhotoKey: string;
        };
        EventBatch: {
            events: components["schemas"]["ParkingEventMessage"][];
        };
        ParkingEventMessage: {
            /** Format: uuid */
            eventId: string;
            /** @enum {string} */
            eventType: "ZONE_ENTERED" | "TOLERANCE_EXCEEDED" | "ZONE_EXITED";
            /** Format: int64 */
            zoneId?: number;
            /** Format: int64 */
            trackId?: number;
            /** @enum {string} */
            vehicleType: "CAR" | "MOTORCYCLE" | "BUS" | "TRUCK";
            /** Format: double */
            detectionConfidence?: number;
            modelVersion: string;
            /** Format: date-time */
            enteredAt: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: double */
            dwellSeconds?: number;
            plate?: components["schemas"]["PlateReading"];
            evidence?: components["schemas"]["EvidenceKeys"];
        };
        PlateReading: {
            value?: string;
            /** Format: double */
            confidence?: number;
            /** @enum {string} */
            status: "READ" | "PENDING_CONFIRMATION" | "NOT_READ";
        };
        EventBatchResult: {
            results?: components["schemas"]["EventResult"][];
        };
        EventResult: {
            /** Format: uuid */
            eventId?: string;
            /** @enum {string} */
            outcome?: "ACCEPTED" | "DUPLICATE" | "REJECTED";
            reason?: string;
            /** Format: uuid */
            reportId?: string;
        };
        LoginResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: date-time */
            expiresAt?: string;
            user?: components["schemas"]["AuthenticatedUser"];
            mfaSetupRequired?: boolean;
        };
        MfaEnrollment: {
            secret?: string;
            otpauthUri?: string;
        };
        MfaCode: {
            code: string;
        };
        LoginRequest: {
            username: string;
            password: string;
            otp?: string;
        };
        ReviewRequest: {
            /** @enum {string} */
            status: "NEW" | "CONFIRMED" | "DISMISSED";
            /** @enum {string} */
            dismissalReason?: "FALSE_POSITIVE" | "MOMENTARY_STOP" | "EMERGENCY_VEHICLE" | "PLATE_MISREAD";
            correctedPlate?: string;
        };
        ReportView: {
            /** Format: uuid */
            id?: string;
            cameraId?: string;
            /** Format: int64 */
            zoneId?: number;
            /** Format: int64 */
            trackId?: number;
            /** @enum {string} */
            vehicleType?: "CAR" | "MOTORCYCLE" | "BUS" | "TRUCK";
            plate?: string;
            /** Format: double */
            plateConfidence?: number;
            /** @enum {string} */
            plateStatus?: "READ" | "PENDING_CONFIRMATION" | "NOT_READ";
            /** Format: double */
            detectionConfidence?: number;
            /** Format: date-time */
            enteredAt?: string;
            /** Format: date-time */
            generatedAt?: string;
            /** Format: date-time */
            exitedAt?: string;
            /** Format: int32 */
            totalSeconds?: number;
            /** @enum {string} */
            status?: "NEW" | "CONFIRMED" | "DISMISSED";
            /** @enum {string} */
            dismissalReason?: "FALSE_POSITIVE" | "MOMENTARY_STOP" | "EMERGENCY_VEHICLE" | "PLATE_MISREAD";
            modelVersion?: string;
            /** Format: uuid */
            reviewedBy?: string;
            /** Format: date-time */
            reviewedAt?: string;
        };
        StatisticsPoint: {
            /** Format: date-time */
            bucket?: string;
            /** Format: int64 */
            zoneId?: number;
            /** Format: int64 */
            vehiclesDetected?: number;
            /** Format: double */
            occupancyPct?: number;
            /** Format: double */
            avgDwellSeconds?: number;
            /** Format: double */
            fps?: number;
            /** Format: double */
            avgConfidence?: number;
        };
        RetrainingStatus: {
            /** Format: int64 */
            pendingSamples?: number;
            /** Format: int32 */
            threshold?: number;
            /** Format: int64 */
            openDriftAlerts?: number;
            retrainingRequired?: boolean;
        };
        PageMetadata: {
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        PagedModelReportView: {
            content?: components["schemas"]["ReportView"][];
            page?: components["schemas"]["PageMetadata"];
        };
        EvidenceUrls: {
            entry?: string;
            report?: string;
            plate?: string;
        };
        ReportDetail: {
            report?: components["schemas"]["ReportView"];
            zone?: components["schemas"]["ZoneSummary"];
            evidenceUrls?: components["schemas"]["EvidenceUrls"];
        };
        ZoneSummary: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            zoneType?: "SIDEWALK" | "CORNER" | "GARAGE_ENTRANCE" | "YELLOW_ZONE" | "TRAFFIC_LANE";
        };
        ActiveModel: {
            version?: string;
            detector?: components["schemas"]["ModelArtifact"];
            plateReader?: components["schemas"]["ModelArtifact"];
        };
        ModelArtifact: {
            url?: string;
            sha256?: string;
        };
        EdgeConfiguration: {
            cameraId?: string;
            /** Format: int64 */
            configVersion?: number;
            frame?: components["schemas"]["FrameSize"];
            zones?: components["schemas"]["ZoneDefinition"][];
            model?: components["schemas"]["ActiveModel"];
            settings?: components["schemas"]["Settings"];
        };
        FrameSize: {
            /** Format: int32 */
            width?: number;
            /** Format: int32 */
            height?: number;
        };
        LiveVideo: {
            /** Format: int32 */
            width?: number;
            /** Format: int32 */
            height?: number;
            /** Format: int32 */
            fps?: number;
            /** Format: double */
            jpegQuality?: number;
        };
        Point: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
        };
        Settings: {
            /** Format: int32 */
            heartbeatIntervalSeconds?: number;
            /** Format: int32 */
            detectionSampleIntervalMs?: number;
            /** Format: int32 */
            analyticsIntervalSeconds?: number;
            /** Format: int32 */
            configPollIntervalSeconds?: number;
            video?: components["schemas"]["LiveVideo"];
        };
        ZoneDefinition: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            zoneType?: "SIDEWALK" | "CORNER" | "GARAGE_ENTRANCE" | "YELLOW_ZONE" | "TRAFFIC_LANE";
            polygon?: components["schemas"]["Point"][];
            /** Format: int32 */
            toleranceSeconds?: number;
            signaled?: boolean;
        };
        CameraView: {
            id?: string;
            name?: string;
            address?: string;
            location?: components["schemas"]["GeoPoint"];
            coverageArea?: components["schemas"]["GeoPoint"][];
            /** @enum {string} */
            displayStatus?: "ONLINE" | "OFFLINE" | "ACTIVE_REPORT";
            /** Format: date-time */
            lastSignalAt?: string;
            frame?: components["schemas"]["FrameSize"];
        };
        GeoPoint: {
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
        };
        AnalyticsSnapshot: {
            /** Format: date-time */
            generatedAt: string;
            /** Format: double */
            fps?: number;
            /** Format: double */
            inferenceLatencyMs?: number;
            oneMinute: components["schemas"]["WindowMetrics"];
            fifteenMinutes: components["schemas"]["WindowMetrics"];
        };
        Box: {
            /** Format: double */
            x1?: number;
            /** Format: double */
            y1?: number;
            /** Format: double */
            x2?: number;
            /** Format: double */
            y2?: number;
        };
        DetectionSnapshot: {
            /** Format: date-time */
            capturedAt: string;
            /** Format: int32 */
            frameWidth?: number;
            /** Format: int32 */
            frameHeight?: number;
            vehicles: components["schemas"]["TrackedVehicle"][];
        };
        LiveView: {
            cameraId?: string;
            connected?: boolean;
            /** Format: date-time */
            lastSignalAt?: string;
            detections?: components["schemas"]["DetectionSnapshot"];
            /** Format: date-time */
            detectionsAt?: string;
            analytics?: components["schemas"]["AnalyticsSnapshot"];
            /** Format: date-time */
            analyticsAt?: string;
        };
        TrackedVehicle: {
            /** Format: int64 */
            trackId?: number;
            /** @enum {string} */
            vehicleType: "CAR" | "MOTORCYCLE" | "BUS" | "TRUCK";
            box: components["schemas"]["Box"];
            /** Format: double */
            confidence?: number;
            /** Format: int64 */
            zoneId?: number;
            /** Format: double */
            stationarySeconds?: number;
        };
        WindowMetrics: {
            /** Format: int32 */
            vehiclesDetected?: number;
            /** Format: double */
            avgDwellSeconds?: number;
            /** Format: int32 */
            reportsGenerated?: number;
            zoneOccupancy: components["schemas"]["ZoneOccupancy"][];
        };
        ZoneOccupancy: {
            /** Format: int64 */
            zoneId?: number;
            /** Format: double */
            occupancyPct?: number;
        };
        AlertView: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            alertType?: "CONFIDENCE_DRIFT" | "BRIGHTNESS_DRIFT" | "DISMISSAL_RATE_DRIFT" | "RETRAINING_REQUIRED" | "UNVERIFIED_MODEL";
            cameraId?: string;
            message?: string;
            /** Format: double */
            observedValue?: number;
            /** Format: double */
            baselineValue?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            acknowledgedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ZoneView"][];
                };
            };
        };
    };
    replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceZonesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ZoneView"][];
                };
            };
        };
    };
    users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticatedUser"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticatedUser"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelVersionView"][];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterModelRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelVersionView"];
                };
            };
        };
    };
    uploadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
                artifact: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelVersionView"];
                };
            };
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelVersionView"];
                };
            };
        };
    };
    rollback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelVersionView"];
                };
            };
        };
    };
    evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    entry: string;
                    /** Format: binary */
                    report: string;
                    /** Format: binary */
                    plate: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EvidenceKeys"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventBatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventBatchResult"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    setupMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MfaEnrollment"];
                };
            };
        };
    };
    activateMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    acknowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportDetail"];
                };
            };
        };
    };
    review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportView"];
                };
            };
        };
    };
    query: {
        parameters: {
            query: {
                from: string;
                to: string;
                zoneId?: number;
                granularity?: "MINUTE" | "HOUR" | "DAY";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatisticsPoint"][];
                };
            };
        };
    };
    retrainingStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RetrainingStatus"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                cameraId?: string;
                zoneId?: number;
                status?: "NEW" | "CONFIRMED" | "DISMISSED";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelReportView"];
                };
            };
        };
    };
    evidence_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
        };
    };
    export: {
        parameters: {
            query: {
                format: "PDF" | "XLSX";
                from?: string;
                to?: string;
                cameraId?: string;
                zoneId?: number;
                status?: "NEW" | "CONFIRMED" | "DISMISSED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    modelArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
                version: string;
                artifact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    activeModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActiveModel"];
                };
            };
        };
    };
    configuration: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeConfiguration"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CameraView"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CameraView"];
                };
            };
        };
    };
    live: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LiveView"];
                };
            };
        };
    };
    alerts: {
        parameters: {
            query?: {
                openOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertView"][];
                };
            };
        };
    };
}
